Update pubspec yml
themisir/flutter-network-logger pull request #15
Opened 2023-03-07 19:12 UTC by erolkaftanoglu

I am updated all version

2023-03-07 19:28 UTC, themisir commented
Teşekkürler kardeş 🙂

2023-03-08 14:20 UTC, erolkaftanoglu commented
ne demek, istediğin bir değişiklik olur ise hızlıca güncelleyebilirim, eline sağlık

2023-03-09 07:51 UTC, themisir requested changes

2023-03-09 08:11 UTC, erolkaftanoglu commented on pubspec.yaml
> +  dio: ^5.0.1
bence çok mantıklı 🚀

2023-03-09 09:00 UTC, themisir approved these changes

2023-03-09 09:01 UTC, merged